### ISSUE TITLE
chktex permissions

### ISSUE THREAD

**Issue by alecglassford** [nscaife/linter-chktex#12]
If I launch Atom from a command line—with either `sudo atom` or `atom`— everything works as expected. But if I launch Atom by clicking on my dock icon for it or from Finder or Spotlight (I'm on Mac OSX Yosemite), I get a `Failed to run /usr/texbin/chktex: spawn chktex ENOENT` error with each save of my tex document and the linter doesn't function.

I'm running from an administrator account and my chktex has execute permissions for all users, so this seems odd to me.

**Comment by lydakis** [comment]
I have the same issue, but I keep getting the same error message regardless if I'm launching Atom from the command line or from Finder/Spotlight

**Comment by balu-** [comment]
got the same problem

**Comment by nscaife** [comment]
I don't have a Mac to troubleshoot this on.  If someone would be willing to look into it and either tell me where the problem is or submit a pull request, it would be greatly appreciated!

**Comment by DrBones** [comment]
The fix from @balu-  works for me too (OSX), could not check yet if it works on any other OS. Thank you anyway :)
