### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by larsfu** [nscaife/linter-chktex#16]
I just installed linter-chktex and I'm getting this error while editing a .tex document:

> Error: ENOENT: no such file or directory, stat ''
>     at Error (native)
>     at fs.statSync (fs.js:854:18)
>     at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
>     at /home/lars/.atom/packages/linter-chktex/lib/linter-chktex.coffee:35:24
>     at Object.provider.lint (/home/lars/.atom/packages/linter-chktex/lib/linter-chktex.coffee:30:20)
>     at Promise.then._this.emitter.emit.linter (/home/lars/.atom/packages/linter/lib/linter-registry.coffee:59:22)
>     at LinterRegistry.triggerLinter (/home/lars/.atom/packages/linter/lib/linter-registry.coffee:58:16)
>     at /home/lars/.atom/packages/linter/lib/linter-registry.coffee:52:17
>     at Array.map (native)
>     at /home/lars/.atom/packages/linter/lib/linter-registry.coffee:50:27

`chktex` is in my path.

**Comment by danielchatfield** [comment]
Am also getting this error.

**Comment by danielchatfield** [comment]
You can bypass the error by setting `executablePath` in settings.

**Comment by nscaife** [comment]
This should be fixed in the latest release!
