### ISSUE TITLE
How do you get chktex to ignore certain things?

### ISSUE THREAD

**Issue by eject-it** [nscaife/linter-chktex#17]
\somethingORother

followed by a linebreak is actually valid synthax. While it is understandable that the machine can not understand everything there must be an option to tell it to shut up.
I don't know if this is a problem with chktex-linter or the atom linter package in general. But other linter implementations seem to feature a dotfile with ignore lists.

**Comment by jgoldfar** [comment]
This is a limitation of chktex, which is configured through command line options or a "chktexrc" file. I recommend looking to the documentation 
https://www.ctan.org/pkg/chktex?lang=en
to see details.

**Comment by nscaife** [comment]
You can use the "chktexArgs" configuration parameter to specify specific errors or warnings to ignore.
