### ISSUE TITLE
Latest release broke the linter.

### ISSUE THREAD

**Issue by danielchatfield** [nscaife/linter-chktex#18]
v1.1.3 works fine on my machine but 1.2.0 doesn't work, it doesn't error it just never reports any of the warnings.

**Comment by Jaszkowic** [comment]
Same here. 1.1.3 is working, but 1.2.0 seems to do nothing. Also, it does not lint in real-time, the linting is only triggered when the file is saved.

**Comment by nscaife** [comment]
Sorry about the trouble.  The latest release seems to fix this issue for me.
