### ISSUE TITLE
BufferedProcessError

### ISSUE THREAD

**Issue by ghost** [nscaife/linter-chktex#21]
After I update all my packages occurred this error message:
BufferedProcessError: Failed to spawn command /Library/TeX/texbin/ . Make sure it's a file, not a directory and it's executable.
    at /Users/IgorDiniz/.atom/packages/linter-chktex/node-modules/atom-linter/lib/helpers.coffee:50:23
    at Emitter.module.exports.Emiter.emit  (%%Localization%%)
    at BufferedProcess.module.exports.Buffered.Process.handleError (%%Localization%%)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:193:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Can Help me?
Thanks
:)

**Comment by anhallbe** [comment]
+1

EDIT: So I solved it by editing **~/.atom/config.cson**:

Make sure your executablePath points to chktex, not its directory:

**Old:**

```
    "linter-chktex":
        executablePath: "/Library/TeX/texbin/"
```

**Fixed:**

```
    "linter-chktex":
        executablePath: "/Library/TeX/texbin/chktex"
```
