### ISSUE TITLE
Problem spawning chktex, though I have it in my PATH (on osx Yosemite)

### ISSUE THREAD

**Issue by guziy** [nscaife/linter-chktex#4]
Hi:

I get this error in Atom:

/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `chktex`. Make sure `chktex` is installed and on your PATH

although 

```
which chktex
```

prints the following

```
/usr/texbin/chktex
```

The files are compiled fine... I am not sure how to solve this..

Thanks

**Comment by nscaife** [comment]
Does it work if you set the `chktexExecutable` parameter listed in the readme to `/usr/texbin`?

**Comment by guziy** [comment]
No it does not:

I tried using folder and executable paths...

Maybe I did something wrong in the cson file...

Below I've copy-pasted the file:

"""
"*":
  "exception-reporting":
    userId: "7b0f20db-21f5-9e50-efb7-362f642534ce"
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "linter-flake8"
      "linter-chktex"
    ]
  editor:
    invisibles: {}
  linter:
    subtleLinterErrors: [
      "flake8"
      "pylint"
    ]
  "linter-pylint":
    executable: "/Users/san/Python/virtualenvs/py3.4/bin/pylint"
  "linter-flake8":
    executableDir: "/Users/san/Python/virtualenvs/py3.4/bin/"
    ignoreErrorCodes: [
      "E501"
    ]
  "linter-chktex":
    chktexExecutable: "/usr/texbin"

"""

Thanks

2015-06-30 8:37 GMT-04:00 Nolen Scaife notifications@github.com:

> Does it work if you set the chktexExecutable parameter listed in the
> readme to /usr/texbin?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Sasha

**Comment by nscaife** [comment]
I'm sorry you're having this problem!  It doesn't look like you did anything wrong.  I don't have a Mac to test on, but I'll check and see if I can get someone else to try to reproduce it.  In the meantime, if anyone can reproduce this and debug it, a pull request would be greatly appreciated!

**Comment by guziy** [comment]
Hi Nolen:

I've changed the

'linter-chktex':
    chktexExecutable: ....

to

'linter-chktex':
    chktexExecutablePath: ....

And it seems working OK.. Probably the example from the settings section in
the README should be changed?

Cheers

2015-06-30 21:19 GMT-04:00 Nolen Scaife notifications@github.com:

> I'm sorry you're having this problem! It doesn't look like you did
> anything wrong. I don't have a Mac to test on, but I'll check and see if I
> can get someone else to try to reproduce it. In the meantime, if anyone can
> reproduce this and debug it, a pull request would be greatly appreciated!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nscaife/linter-chktex/issues/4#issuecomment-117385296
> .

## 

Sasha

**Comment by nscaife** [comment]
You're right! Bad documentation on my part :hankey: 

I'll fix it, and thanks for reporting back!

**Comment by JonnyCBB** [comment]
@nscaife just so you are aware the README says

```
'linter-chktex':
    executablePath: "C:\\texlive\\2014\\bin\\win32"
```

But this didn't work for me. When I changed the text in the file to 

```
'linter-chktex':
    chktexExecutablePath: "C:\\texlive\\2014\\bin\\win32"
```

as mentioned above then it worked for me. I believe this should be changed in the README.

Thanks for the package btw. It's awesome :+1:

**Comment by dragonxlwang** [comment]
Sorry to bring up this questions again, but although explicating setting the exe path works for me, it cannot read from PATH to set it by itself...

**Comment by ghost** [comment]
Oh thanks, i'll need work in látex all day... Thanks, bro

**Comment by IgorCaetano** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjdIVzMzZjljRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGQ2ZTVmODA2MGFhODdhM2FiYjJjMDc1MGZiZWVjZmExNWMzZmRjMmE4MzZjMTU5MmNmMDAwMDAwMDExMjYzNTUwMjkyYTE2OWNlMDU3Y2ZkYzVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.LyqFdnhzy4T6gbrqwYZGAlOKk1t68TZE6fxvmPKOfl4> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjdIVzMzZjljRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGQ2ZTVmODA2MGFhODdhM2FiYjJjMDc1MGZiZWVjZmExNWMzZmRjMmE4MzZjMTU5MmNmMDAwMDAwMDExMjYzNTUwMjkyYTE2OWNlMDU3Y2ZkYzVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.LyqFdnhzy4T6gbrqwYZGAlOKk1t68TZE6fxvmPKOfl4> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by43SFczM2Y5Y0VlV1c5aEw2MHItYUtRIiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDBkNmU1ZjgwNjBhYTg3YTNhYmIyYzA3NTBmYmVlY2ZhMTVjM2ZkYzJhODM2YzE1OTJjZjAwMDAwMDAxMTI2MzU1MDI5MmExNjljZTA1N2NmZGM1QHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLjdIVzMzZjljRWVXVzloTDYwci1hS1EifX0sInVzZXJJZCI6LTF9.BvG5wQ_Rtt75RzZ-dgj3z0eX6iad7FC76pGAml-4IMk>


Igor Caetano Diniz thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49NzFjNmM2ODYzMmMxOTVjMjJmYTRjZTFhYjY3YjZkOGEmZW1haWw9cmVwbHkrMDBkNmU1ZjgwNjBhYTg3YTNhYmIyYzA3NTBmYmVlY2ZhMTVjM2ZkYzJhODM2YzE1OTJjZjAwMDAwMDAxMTI2MzU1MDI5MmExNjljZTA1N2NmZGM1QHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1uc2NhaWZlL2xpbnRlci1jaGt0ZXg_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwZDZlNWY4MDYwYWE4N2EzYWJiMmMwNzUwZmJlZWNmYTE1YzNmZGMyYTgzNmMxNTkyY2YwMDAwMDAwMTEyNjM1NTAyOTJhMTY5Y2UwNTdjZmRjNUByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by43SFczM2Y5Y0VlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.gFOis685Kc_P10fOtcPyAJLHL-4TOzxnbl_0KSC_5Lw>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by43SFczM2Y5Y0VlV1c5aEw2MHItYUtRJnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGQ2ZTVmODA2MGFhODdhM2FiYjJjMDc1MGZiZWVjZmExNWMzZmRjMmE4MzZjMTU5MmNmMDAwMDAwMDExMjYzNTUwMjkyYTE2OWNlMDU3Y2ZkYzVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.e7kZJGeEtGJozap-McyAws8KcNadmqV6ibnMqfZkE2g> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwZDZlNWY4MDYwYWE4N2EzYWJiMmMwNzUwZmJlZWNmYTE1YzNmZGMyYTgzNmMxNTkyY2YwMDAwMDAwMTEyNjM1NTAyOTJhMTY5Y2UwNTdjZmRjNUByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by43SFczM2Y5Y0VlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.82QBZxPi1HKXiQyIrKBGcGSL4Hoe07WxVcA0erlnHLk>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwZDZlNWY4MDYwYWE4N2EzYWJiMmMwNzUwZmJlZWNmYTE1YzNmZGMyYTgzNmMxNTkyY2YwMDAwMDAwMTEyNjM1NTAyOTJhMTY5Y2UwNTdjZmRjNUByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by43SFczM2Y5Y0VlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.r4qhIefo2RVIC-wKf8AUCyfhrM1PC1Bfw_sSlurbOD0> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS83REtNVTlXZmhPNk84YVlsRGszaWE5MGFSdDZrT1FPWHBXQVNNUmh2dFhiTlRPZVNFLWxTczlhLTAycVQ0SnVGd21TSmRpSVh6cVVrcTRyem45eGRTQS5PbHhkMUZUZENNcVd0QWMxRWRnZFVRLmx1ajh1a3B5cTliaFlKMTQ4QWkxOEVtcC1MbVYtY1BPUE5hc3B5R1VuU2Z6Y0lyR3ZVZlgybVJQZGdmb2lxX0JTMU0ydkVMRTR5WUtBelRlV1FCX3ZvNWRUeFJLQURBNjJMdXZXc0pfZFhKN2VucnA5QUd1U2pHbWh1TGxVcU50bmtTRVFvd1h0ZlBXZkkxcGpyR09HYXk0cFhZNFJhMWg1eldfT25fVmhablpmN29JMzVDc2o4aXhOUUZlTTdMaEdRNHpuNXN4alExTjR0d0MxbHJGNmxTdkg1bjBJN0l3Qk5hS3Fxd0J0c0wwOWoxRVZnWkVCNDRlVnVDZHZ0cTYyMjRaZkNBUHczVkVnMXdOamdZLU9PejhudHo3RlNzTmhiamJ5MW55SnpzP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjdIVzMzZjljRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGQ2ZTVmODA2MGFhODdhM2FiYjJjMDc1MGZiZWVjZmExNWMzZmRjMmE4MzZjMTU5MmNmMDAwMDAwMDExMjYzNTUwMjkyYTE2OWNlMDU3Y2ZkYzVAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uN0hXMzNmOWNFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.hGOjlEDMm1P-X_DkHly0hLouXiq3gAdluzwWodp4G8Y>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA
