### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by Cortys** [nscaife/linter-chktex#5]
AtomLinter v0.X.Y API has been deprecated.
https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API

**Comment by nscaife** [comment]
Thanks for reporting this.  Unfortunately, it looks like this may take some rewriting, so it may be a couple of weeks before I can get to it.

**Comment by nscaife** [comment]
Fixed in #7.  Thanks @PetePriority!
