### ISSUE TITLE
Different behavior from running chktex from terminal

### ISSUE THREAD

**Issue by jhrmnn** [nscaife/linter-chktex#9]
Compared to running `chktex <file>` in the terminal, it seems that in Atom:
- The `chktex` run from Atom ignores any user `.chktexrc`, either in `$HOME` or the current directory. Is this because of some sandboxing?
- I'm also getting warning 21 from `\notag\\` which I'm not getting from the terminal run. This I don't understand as the warning seems valid.

**Comment by nscaife** [comment]
Thanks for letting me know! I'm not sure about warning 21 -- can you send me a minimal TeX sample that will reproduce this?

As for `.chktexrc`, you are correct that this package won't use one if you have it.  It's on my list of features to add, alongside customizable configuration from Atom directly.  I apologize I haven't had a lot of time lately to get this fixed up!

**Comment by nscaife** [comment]
Since I haven't heard anything else, I'm going to close this issue.  Feel free to resubmit if you are able to reproduce the issue!
